name = "Zarya"
realName = "Aleksandra Zaryanova"
age = 28
role = "tank"
sex = "female"

tags = [ "zarya_(overwatch)", "aleksandra_zaryanova" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.brick]
  name = "Brick"
  rarity = "rare"
[skins.goldenrod]
  name = "Goldenrod"
  rarity = "rare"
[skins.taiga]
  name = "Taiga"
  rarity = "rare"
[skins.violet]
  name = "Violet"
  rarity = "rare"
[skins.dawn]
  name = "Dawn"
  rarity = "epic"
[skins.midnight]
  name = "Midnight"
  rarity = "epic"
[skins.frosted]
  name = "Frosted"
  rarity = "epic"
  event = "Winter Wonderland"
[skins.barbarian]
  name = "Barbarian"
  rarity = "legendary"
  tags = [ "barbarian_zarya_(overwatch)", "barbarian_zarya" ]
[skins.arctic]
  name = "Arctic"
  rarity = "legendary"
  tags = [ "arctic_zarya_(overwatch)" ]
[skins.siberian-front]
  name = "Siberian Front"
  rarity = "legendary"
  tags = [ "siberian_front_zarya_(overwatch)" ]
[skins.cybergoth]
  name = "Cybergoth"
  rarity = "legendary"
  tags = [ "cybergoth_zarya_(overwatch)" ]
[skins.industrial]
  name = "Industrial"
  rarity = "legendary"
  tags = [ "industrial_zarya_(overwatch)" ]
[skins.cyberian]
  name = "Cyberian"
  rarity = "legendary"
  event = "Summer Games"
[skins.champion]
  name = "Champion"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "champion_zarya_(overwatch)" ]
[skins.weightlifter]
  name = "Weightlifter"
  rarity = "legendary"
  event = "Overwatch Anniversary"
[skins.totally-80s]
  name = "Totally 80's" # should be "Totally '80"
  rarity = "legendary"
  event = "Halloween Terror"
[skins.xuanwu]
  name = "Xuanwu"
  rarity = "legendary"
  event = "Lunar New Year"
