language: go
go:
  - 1.10.x
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

script:
  - make build

notifications:
  email: false
