[metadata.heroku]
  root-package = "github.com/overwaifu/overwaifu"
  go-version = "go1.10"
  install = [ "./cmd/..." ]
  ensure = true

[prune]
  unused-packages = true
  go-tests = true

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"

[[constraint]]
  name = "github.com/globalsign/mgo"
  branch = "master"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "1.2.0"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"

[[constraint]]
  name = "github.com/leonidboykov/getmoe"
  version = "0.2.0"
