name = "Doomfist"
realName = "Akande Ogundimu"
age = 45
role = "offense"
sex = "male"

tag = "doomfist_(overwatch)"

[skins]
  [skins.classic]
    name = "Classic"
    rarity = "common"
  [skins.daisy]
    name = "Daisy"
    rarity = "Rare"
  [skins.lake]
    name = "Lake"
    rarity = "rare"
  [skins.plains]
    name = "Plains"
    rarity = "rare"
  [skins.sunset]
    name = "Sunset"
    rarity = "rare"
  [skins.leopard]
    name = "Leopard"
    rarity = "epic"
  [skins.painted]
    name = "Painted"
    rarity = "epic"
  [skins.avatar]
    name = "Avatar"
    rarity = "legendary"
  [skins.spirit]
    name = "Spirit"
    rarity = "legendary"
  [skins.caution]
    name = "Caution"
    rarity = "legendary"
  [skins.irin]
    name = "Irin"
    rarity = "legendary"
