name = "D.Va"
realName = "Hana Song"
age = 19
role = "tank"
sex = "female"

tags = [ "d.va_(overwatch)", "hana_song" ]

[skins]
  [skins.classic]
    name = "Classic"
    rarity = "common"
  [skins.blueberry]
    name = "Blueberry"
    rarity = "rare"
  [skins.lemon-lime]
    name = "Lemon-Lime"
    rarity = "rare"
  [skins.tangerine]
    name = "Tangerine"
    rarity = "rare"
  [skins.watermelon]
    name = "Watermelon"
    rarity = "rare"
  [skins.carbon-fiber]
    name = "Carbon Fiber"
    rarity = "epic"
  [skins.white-rabbit]
    name = "White Rabbit"
    rarity = "epic"
  [skins.taegeukgi]
    name = "Taegeukgi"
    rarity = "epic"
    event = "Summer Games"
    tags = [ "taegeukgi_d.va_(overwatch)", "taegukgi_d.va" ]
  [skins.junker]
    name = "Junker"
    rarity = "legendary"
    tags = [ "junker_d.va_(overwatch)", "junker_d.va" ]
  [skins.scavenger]
    name = "Scavenger"
    rarity = "legendary"
    tags = [ "scavenger_d.va_(overwatch)", "scavenger_d.va" ]
  [skins.bva]
    name = "B.Va"
    rarity = "legendary"
    tags = [ "b.va_(overwatch)", "b.va" ]
  [skins.junebug]
    name = "Junebug"
    rarity = "legendary"
    tags = [ "junebug_d.va_(overwatch)", "junebug_d.va" ]
  [skins.palanquin]
    name = "Palanquin"
    rarity = "legendary"
    event = "Year of the Rooster"
    tags = [ "palanquin_d.va" ]
  [skins.cruiser]
    name = "Cruiser"
    rarity = "legendary"
    event = "Overwatch Anniversary"
    tags = [ "cruiser_d.va" ]
  [skins.police-officer]
    name = "Police Officer"
    rarity = "legendary"
    event = "Heroes of the Storm"
    tags = [ "officer_d.va", "police_officer_d.va" ]
  [skins.black-cat]
    name = "Black Cat"
    rarity = "legendary"
    tags = [ "black_cat_d.va" ]
