name = "Genji"
slug = "genji"
realName = "Genji Shimada"
age = 35
role = "offense"
sex = "male"

# there are no `genji_(overwatch)` tag on sankaku
tag = "shimada_genji"

[[skins]]
  name = "Classic"
  rarity = "common"
[[skins]]
  name = "Azurite"
  rarity = "rare"
[[skins]]
  name = "Cinnabar"
  rarity = "rare"
[[skins]]
  name = "Malachite"
  rarity = "rare"
[[skins]]
  name = "Ochre"
  rarity = "rare"
[[skins]]
  name = "Carbon Fiber"
  rarity = "epic"
[[skins]]
  name = "Chrome"
  rarity = "epic"
[[skins]]
  name = "Nihon"
  rarity = "epic"
  event = "Summer Games"
[[skins]]
  name = "Sparrow"
  rarity = "legendary"
  tag = "sparrow_genji_(overwatch)"
[[skins]]
  name = "Young Genji"
  rarity = "legendary"
  tag = "young_genji_(overwatch)"
[[skins]]
  name = "Bedouin"
  rarity = "legendary"
  tag = "bedouin_genji_(overwatch)"
[[skins]]
  name = "Nomad"
  rarity = "legendary"
  tag = "nomad_genji_(overwatch)"
[[skins]]
  name = "Blackwatch"
  rarity = "legendary"
  event = "Uprising"
  tag = "blackwatch_genji_(overwatch)"
[[skins]]
  name = "Sentai"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tag = "sentai_genji_(overwatch)"
[[skins]]
  name = "Oni"
  rarity = "legendary"
  event = "Heroes of the Storm"
  tag = "oni_genji_(overwatch)"
