name = "Hanzo"
slug = "hanzo"
realName = "Hanzo Shimada"
age = 38
role = "defense"
sex = "male"

# there are no `hanzo_(overwatch)` tag on sankaku
tag = "shimada_hanzo"

[[skins]]
  name = "Classic"
  rarity = "common"
[[skins]]
  name = "Azuki"
  rarity = "rare"
[[skins]]
  name = "Kinoko"
  rarity = "rare"
[[skins]]
  name = "Midori"
  rarity = "rare"
[[skins]]
  name = "Sora"
  rarity = "rare"
[[skins]]
  name = "Cloud"
  rarity = "epic"
[[skins]]
  name = "Dragon"
  rarity = "epic"
[[skins]]
  name = "Demon"
  rarity = "epic"
  event = "Halloween Terror"
  tag = "demon_hanzo_(overwatch)"
[[skins]]
  name = "Young Hanzo"
  rarity = "legendary"
  tag = "young_hanzo_(overwatch)"
[[skins]]
  name = "Young Master"
  rarity = "legendary"
  tag = "young_master_hanzo_(overwatch)"
[[skins]]
  name = "Lone Wolf"
  rarity = "legendary"
  tag = "lone_wolf_hanzo"
[[skins]]
  name = "Okami"
  rarity = "legendary"
  tag = "okami_hanzo_(overwatch)"
[[skins]]
  name = "Cyberninja"
  rarity = "legendary"
  event = "Overwatch Anniversary"
