name = "Junkrat"
slug = "junkrat"
realName = "Jamison Fawkes"
age = 25
role = "defense"
sex = "male"

tag = "junkrat_(overwatch)"

[[skins]]
  name = "Classic"
  rarity = "common"
[[skins]]
  name = "Bleached"
  rarity = "rare"
[[skins]]
  name = "Drowned"
  rarity = "rare"
[[skins]]
  name = "Irradiated"
  rarity = "rare"
[[skins]]
  name = "Rusted"
  rarity = "rare"
[[skins]]
  name = "Jailbird"
  rarity = "epic"
[[skins]]
  name = "Toasted"
  rarity = "epic"
[[skins]]
  name = "Firework"
  rarity = "epic"
  event = "Year of the Rooster"
  tag = "firework_junkrat_(overwatch)"
[[skins]]
  name = "Fool"
  rarity = "legendary"
  tag = "fool_junkrat_(overwatch)"
[[skins]]
  name = "Jester"
  rarity = "legendary"
  tag = "jester_junkrat_(overwatch)"
[[skins]]
  name = "Hayseed"
  rarity = "legendary"
  tag = "hayseed_junkrat_(overwatch)"
[[skins]]
  name = "Scarecrow"
  rarity = "legendary"
[[skins]]
  name = "Cricket"
  rarity = "legendary"
  event = "Summer Games"
[[skins]]
  name = "Dr. Junkenstein"
  rarity = "legendary"
  event = "Halloween Terror"
  tag = "dr._junkenstein_junkrat_(overwatch)"
