name = "McCree"
realName = "Jesse McCree"
age = 37
role = "offense"
sex = "male"

# there are no `mccree_(overwatch)` tags on[  sankaku ]
tags = [ "jesse_mccree" ]

[skins]
  [skins.classic]
    name = "classic"
    rarity = "common"
  [skins.ebony]
    name = "Ebony"
    rarity = "rare"
  [skins.lake]
    name = "Lake"
    rarity = "rare"
  [skins.sage]
    name = "Sage"
    rarity = "rare"
  [skins.wheat]
    name = "Wheat"
    rarity = "rare"
  [skins.on-the-range]
    name = "On the Range"
    rarity = "epic"
  [skins.white-hat]
    name = "White Hat"
    rarity = "epic"
  [skins.american]
    name = "American"
    rarity = "epic"
    event = "Summer Games"
    tags = [ "american_mccree" ]
  [skins.scrooge]
    name = "Scrooge"
    rarity = "epic"
    event = "Winter Wonderland"
    tags = [ "scrooge_mccree_(overwatch)" ]
  [skins.gambler]
    name = "Gambler"
    rarity = "legendary"
    tags = [ "gambler_mccree_(overwatch)" ]
  [skins.riverboat]
    name = "Riverboat"
    rarity = "legendary"
  [skins.mystery-man]
    name = "Mystery Man"
    rarity = "legendary"
    tags = [ "mystery_man_mccree" ]
  [skins.vigilante]
    name = "Vigilante"
    rarity = "legendary"
    tags = [ "vigilante_mccree_(overwatch)" ]
  [skins.blackwatch]
    name = "Blackwatch"
    rarity = "legendary"
    event = "Uprising"
    tags = [ "blackwatch_mccree_(overwatch)" ]
  [skins.lifeguard]
    name = "Lifeguard"
    rarity = "legendary"
    event = "Summer Games"
    tags = [ "lifeguard_mccree_(overwatch)" ]
  [skins.van-helsing]
    name = "Van Helsing"
    rarity = "legendary"
    event = "Halloween Terror"
