name = "McCree"
realName = "Jesse McCree"
age = 37
role = "offense"
sex = "male"

# there are no `mccree_(overwatch)` tag on sankaku
tag = "jesse_mccree"

[skins]
  [skins.classic]
    name = "classic"
    rarity = "common"
  [skins.ebony]
    name = "Ebony"
    rarity = "rare"
  [skins.lake]
    name = "Lake"
    rarity = "rare"
  [skins.sage]
    name = "Sage"
    rarity = "rare"
  [skins.wheat]
    name = "Wheat"
    rarity = "rare"
  [skins.on-the-range]
    name = "On the Range"
    rarity = "epic"
  [skins.white-hat]
    name = "White Hat"
    rarity = "epic"
  [skins.american]
    name = "American"
    rarity = "epic"
    event = "Summer Games"
    tag = "american_mccree"
  [skins.scrooge]
    name = "Scrooge"
    rarity = "epic"
    event = "Winter Wonderland"
    tag = "scrooge_mccree_(overwatch)"
  [skins.gambler]
    name = "Gambler"
    rarity = "legendary"
    tag = "gambler_mccree_(overwatch)"
  [skins.riverboat]
    name = "Riverboat"
    rarity = "legendary"
  [skins.mystery-man]
    name = "Mystery Man"
    rarity = "legendary"
    tag = "mystery_man_mccree"
  [skins.vigilante]
    name = "Vigilante"
    rarity = "legendary"
    tag = "vigilante_mccree_(overwatch)"
  [skins.blackwatch]
    name = "Blackwatch"
    rarity = "legendary"
    event = "Uprising"
    tag = "blackwatch_mccree_(overwatch)"
  [skins.lifeguard]
    name = "Lifeguard"
    rarity = "legendary"
    event = "Summer Games"
    tag = "lifeguard_mccree_(overwatch)"
  [skins.van-helsing]
    name = "Van Helsing"
    rarity = "legendary"
    event = "Halloween Terror"
