name = "Mercy"
realName = "Angela Ziegler"
age = 37
role = "support"
sex = "female"

tags = [ "mercy_(overwatch)", "angela_ziegler" ]

[skins]
  [skins.classic]
    name = "Classic"
    rarity = "common"
  [skins.celestial]
  	name = "Celestial"
  	rarity = "rare"
  [skins.mist]
  	name = "Mist"
  	rarity = "rare"
  [skins.orchid]
  	name = "Orchid"
  	rarity = "rare"
  [skins.verdant]
  	name = "Verdant"
  	rarity = "rare"
  [skins.amber]
  	name = "Amber"
  	rarity = "epic"
  [skins.cobalt]
  	name = "Cobalt"
  	rarity = "epic"
  	tags = [ "cobalt_mercy_(overwatch)", "cobalt_mercy" ]
  [skins.fortune]
  	name = "Fortune"
  	rarity = "epic"
    event = "Year of the Rooster"
  	tags = [ "fortune_mercy_(overwatch)", "fortune_mercy" ]
  [skins.eidgenossin]
  	name = "Eidgenossin"
  	rarity = "epic"
  	event = "Summer Games"
  	tags = [ "eidgenossin_mercy_(overwatch)" ]
  [skins.sigrun]
  	name = "Sigrún"
  	rarity = "legendary"
  	tags = [ "sigrun_mercy_(overwatch)", "sigrun_mercy" ]
  [skins.valkyrie]
  	name = "Valkyrie"
  	rarity = "legendary"
  	tags = [ "valkyrie_mercy_(overwatch)", "valkyrie_mercy" ]
  [skins.devil]
  	name = "Devil"
  	rarity = "legendary"
  	tags = [ "devil_mercy_(overwatch)", "devil_mercy" ]
  [skins.imp]
  	name = "Imp"
  	rarity = "legendary"
  	tags = [ "imp_mercy" ]
  [skins.witch]
  	name = "Witch"
  	rarity = "legendary"
  	event = "Helloween Terror"
  	tags = [ "witch_mercy_(overwatch)", "witch_mercy" ]
  [skins.combat-medic-ziegler]
  	name = "Combat Medic Ziegler"
  	rarity = "legendary"
  	event = "Uprising"
  	tags = [ "combat_medic_ziegler_(overwatch)", "combat_medic_ziegler" ]
  [skins.winged-victory]
  	name = "Winged Victory"
  	rarity = "legendary"
  	event = "Summer Games"
  	tags = [ "winged_victory_mercy_(overwatch)", "winged_victory_mercy" ]
