name = "Orisa" # Yep, robocow
realName = "Orisa"
age = 1 # Month
role = "tank"
sex = "female"

tags = [ "orisa_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.dawn]
  name = "Dawn"
  rarity = "rare"
[skins.plains]
  name = "Plains"
  rarity = "rare"
[skins.sunrise]
  name = "Sunrise"
  rarity = "rare"
[skins.twilight]
  name = "Twilight"
  rarity = "rare"
[skins.camouflage]
  name = "Camouflage"
  rarity = "epic"
[skins.or15]
  name = "OR15"
  rarity = "epic"
[skins.immortal]
  name = "Immortal"
  rarity = "legendary"
[skins.dynastinae]
  name = "Dynastinae"
  rarity = "legendary"
[skins.megasoma]
  name = "Megasoma"
  rarity = "legendary"
  tags = [ "megasoma_orisa" ]
[skins.carbon-fiber]
  name = "Carbon Fiber"
  rarity = "legendary"
[skins.protector]
  name = "Protector"
  rarity = "legendary"
[skins.null-sector]
  name = "Null Sector"
  rarity = "legendary"
  event = "Uprising"
