name = "Roadhog"
realName = "Mako Rutledge"
age = 48
role = "tank"
sex = "male"

tag = "roadhog_(overwatch)"

[skins]
  [skins.classic]
    name = "Classic"
    rarity = "common"
  [skins.kiwi]
    name = "Kiwi"
    rarity = "rare"
  [skins.mud]
    name = "Mud"
    rarity = "rare"
  [skins.sand]
    name = "Sand"
    rarity = "rare"
  [skins.thistle]
    name = "Thistle"
    rarity = "rare"
  [skins.pigpen]
    name = "Pigpen"
    rarity = "epic"
  [skins.stitched]
    name = "Stitched"
    rarity = "epic"
  [skins.rudolph]
    name = "Rudolph"
    rarity = "epic"
    event = "Winter Wonderland"
  [skins.islander]
    name = "Islander"
    rarity = "legendary"
  [skins.toa]
    name = "Toa"
    rarity = "legendary"
  [skins.mako]
    name = "Mako"
    rarity = "legendary"
  [skins.sharkbait]
    name = "Sharkbait"
    rarity = "legendary"
    tag = "sharkbait_roadhog_(overwatch)"
  [skins.junkensteins-monster]
    name = "Junkenstein's Monster"
    rarity = "legendary"
    event = "Halloween Terror"
    tag = "junkenstein's_monster_roadhog_(overwatch)"
  [skins.ice-fisherman]
    name = "Ice Fisherman"
    rarity = "legendary"
    event = "Winter Wonderland"
