name = "Roadhog"
slug = "roadhog"
realName = "Mako Rutledge"
age = 48
role = "tank"
sex = "male"

tag = "roadhog_(overwatch)"

[[skins]]
  name = "Classic"
  rarity = "common"
[[skins]]
  name = "Kiwi"
  rarity = "rare"
[[skins]]
  name = "Mud"
  rarity = "rare"
[[skins]]
  name = "Sand"
  rarity = "rare"
[[skins]]
  name = "Thistle"
  rarity = "rare"
[[skins]]
  name = "Pigpen"
  rarity = "epic"
[[skins]]
  name = "Stitched"
  rarity = "epic"
[[skins]]
  name = "Rudolph"
  rarity = "epic"
  event = "Winter Wonderland"
[[skins]]
  name = "Islander"
  rarity = "legendary"
[[skins]]
  name = "Toa"
  rarity = "legendary"
[[skins]]
  name = "Mako"
  rarity = "legendary"
[[skins]]
  name = "Sharkbait"
  rarity = "legendary"
  tag = "sharkbait_roadhog_(overwatch)"
[[skins]]
  name = "Junkenstein's Monster"
  rarity = "legendary"
  event = "Halloween Terror"
  tag = "junkenstein's_monster_roadhog_(overwatch)"
