name = "Sombra"
realName = "Olivia Colomar"
age = 30
role = "offense"
sex = "female"

tag = "sombra_(overwatch)"

[skins]
  [skins.classic]
    name = "Classic"
    rarity = "common"
  [skins.cidro]
    name = "Cidro"
    rarity = "rare"
  [skins.incendio]
    name = "Incendio"
    rarity = "rare"
  [skins.mar]
    name = "Mar"
    rarity = "rare"
  [skins.noche]
    name = "Noche"
    rarity = "rare"
  [skins.glitch]
    name = "Glitch"
    rarity = "epic"
  [skins.virus]
    name = "Virus"
    rarity = "epic"
    tag = "virus_sombra_(overwatch)"
  [skins.peppermint]
    name = "Peppermint"
    rarity = "epic"
    event = "Winter Wonderland"
    tag = "peppermint_sombra_(overwatch)"
  [skins.azucar]
    name = "Azúcar"
    rarity = "legendary"
    tag = "azucar_sombra_(overwatch)"
  [skins.los-muertos]
    name = "Los Muertos"
    rarity = "legendary"
    tag = "los_muertos_sombra_(overwatch)"
  [skins.augmented]
    name = "Augmented"
    rarity = "legendary"
    tag = "augmented_sombra_(overwatch)"
  [skins.cyberspace]
    name = "Cyberspace"
    rarity = "legendary"
    tag = "cyberspace_sombra_(overwatch)"
  [skins.tulum]
    name = "Tulum"
    rarity = "legendary"
    event = "Summer Games"
    tag = "tulum_sombra_(overwatch)"
  [skins.rime]
    name = "Rime"
    rarity = "legendary"
    event = "Summer Games"
