name = "Sombra"
slug = "sombra"
realName = "Olivia Colomar"
age = 30
role = "offense"
sex = "female"

tag = "sombra_(overwatch)"

[[skins]]
  name = "Classic"
  slug = "classic"
  rarity = "common"
[[skins]]
  name = "Cidro"
  slug = "cidro"
  rarity = "rare"
[[skins]]
  name = "Incendio"
  slug = "incendio"
  rarity = "rare"
[[skins]]
  name = "Mar"
  slug = "mar"
  rarity = "rare"
[[skins]]
  name = "Noche"
  slug = "noche"
  rarity = "rare"
[[skins]]
  name = "Glitch"
  slug = "glitch"
  rarity = "epic"
[[skins]]
  name = "Virus"
  slug = "virus"
  rarity = "epic"
[[skins]]
  name = "Peppermint"
  slug = "peppermint"
  rarity = "epic"
  event = "Winter Wonderland"
  tag = "peppermint_sombra_(overwatch)"
[[skins]]
  name = "Azúcar"
  slug = "azucar"
  rarity = "legendary"
[[skins]]
  name = "Los Muertos"
  slug = "los-muertos"
  rarity = "legendary"
  tag = "los_muertos_sombra_(overwatch)"
[[skins]]
  name = "Augmented"
  slug = "augmented"
  rarity = "legendary"
  tag = "augmented_sombra_(overwatch)"
[[skins]]
  name = "Cyberspace"
  slug = "cyberspace"
  rarity = "legendary"
  tag = "cyberspace_sombra_(overwatch)"
[[skins]]
  name = "Tulum"
  slug = "tulum"
  rarity = "legendary"
  event = "Summer Games"
  tag = "tulum_sombra_(overwatch)"
