name = "Symmetra"
realName = "Satya Vaswani"
age = 28
role = "support"
sex = "female"

tag = "symmetra_(overwatch)"

[skins]
  [skins.classic]
    name = "Classic"
    rarity = "common"
  [skins.cardamom]
    name = "Cardamom"
    rarity = "rare"
  [skins.hyacinth]
    name = "Hyacinth"
    rarity = "rare"
  [skins.saffron]
    name = "Saffron"
    rarity = "rare"
  [skins.technomancer]
    name = "Technomancer"
    rarity = "rare"
  [skins.regal]
    name = "Regal"
    rarity = "epic"
  [skins.utopaea]
    name = "Utopaea"
    rarity = "epic"
  [skins.qipao]
    name = "Qipao"
    rarity = "epic"
    event = "Year of the Rooster"
  [skins.vampire]
    name = "Vampire"
    rarity = "epic"
    event = "Halloween Terror"
    tag = "vampire_symmetra_(overwatch)"
  [skins.architech]
    name = "Architech"
    rarity = "legendary"
  [skins.vishkar]
    name = "Vishkar"
    rarity = "legendary"
    tag = "vishkar_symmetra_(overwatch)"
  [skins.devi]
    name = "Devi"
    rarity = "legendary"
    tag = "devi_symmetra_(overwatch)"
  [skins.goddess]
    name = "Goddess"
    rarity = "legendary"
    tag = "goddess_symmetra"
  [skins.oasis]
    name = "Oasis"
    rarity = "legendary"
    event = "Overwatch Anniversary"
    tag = "oasis_symmetra_(overwatch)"
  [skins.dragon]
    name = "Dragon"
    rarity = "legendary"
    event = "Halloween Terror"
    tag = "dragon_symmetra_(overwatch)"
