name = "Widowmaker"
realName = "Amélie Lacroix"
age = 33
occupation = "Annecy France"
role = "defense"
sex = "female"

tag = "widowmaker_(overwatch)"

[[skins]]
  name = "Classic"
  rarity = "common"
[[skins]]
  name = "Ciel"
  rarity = "rare"
[[skins]]
  name = "Nuit"
  rarity = "rare"
[[skins]]
  name = "Rose"
  rarity = "rare"
[[skins]]
  name = "Vert"
  rarity = "rare"
[[skins]]
  name = "Patina"
  rarity = "epic"
[[skins]]
  name = "Winter"
  rarity = "epic"
[[skins]]
  name = "Tricolore"
  rarity = "epic"
  event = "Summer Games"
  tag = "tricolore_widowmaker_(overwatch)"
[[skins]]
  name = "Odette"
  rarity = "legendary"
  tag = "odette_widowmaker_(overwatch)"
[[skins]]
  name = "Odile"
  rarity = "legendary"
  tag = "odile_widowmaker_(overwatch)"
[[skins]]
  name = "Comtesse"
  rarity = "legendary"
  tag = "comtesse_widowmaker_(overwatch)"
[[skins]]
  name = "Huntress"
  rarity = "legendary"
  tag = "huntress_widowmaker_(overwatch)"
[[skins]]
  name = "Talon"
  rarity = "legendary"
  event = "Uprising"
  tag = "talon_widowmaker_(overwatch)"
[[skins]]
  name = "Côte d'Azur"
  rarity = "legendary"
  event = "Summer Games"
  tag = "cote_d'azur_widowmaker"
[[skins]]
  name = "Noire"
  rarity = "legendary"
  event = "Pre-order"
  tag = "noire_widowmaker_(overwatch)"
