name = "Winston" # Yep, monkey
slug = "winston"
realName = "Winston"
age = 29
role = "tank"
sex = "male"

tag = "winston_(overwatch)"

[[skins]]
  name = "Classic"
  rarity = "common"
[[skins]]
  name = "Atmosphere"
  rarity = "rare"
[[skins]]
  name = "Banana"
  rarity = "rare"
[[skins]]
  name = "Forest"
  rarity = "rare"
[[skins]]
  name = "Red Planet"
  rarity = "rare"
[[skins]]
  name = "Desert"
  rarity = "epic"
[[skins]]
  name = "Horizon"
  rarity = "epic"
[[skins]]
  name = "BlizzCon 2017"
  rarity = "epic"
  event = "BlizzCon 2017"
[[skins]]
  name = "Frogston"
  rarity = "legendary"
[[skins]]
  name = "Undersea"
  rarity = "legendary"
[[skins]]
  name = "Explorer"
  rarity = "legendary"
[[skins]]
  name = "Safari"
  rarity = "legendary"
[[skins]]
  name = "Wukong"
  rarity = "legendary"
  event = "Year of the Rooster"
  tag = "wukong_winston_(overwatch)"
[[skins]]
  name = "Yeti"
  rarity = "legendary"
  event = "Winter Wonderland"
