name = "D.Va"
realName = "Hana Song"
age = 19
role = "tank"
sex = "female"

tags = [ "d.va_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.blueberry]
  name = "Blueberry"
  rarity = "rare"
  tags = [ "blueberry_d.va" ]
[skins.lemon-lime]
  name = "Lemon-Lime"
  rarity = "rare"
  tags = [ "lemon-lime_d.va" ]
[skins.tangerine]
  name = "Tangerine"
  rarity = "rare"
  tags = [ "tangerine_d.va" ]
[skins.watermelon]
  name = "Watermelon"
  rarity = "rare"
  tags = [ "watermelon_d.va" ]
[skins.carbon-fiber]
  name = "Carbon Fiber"
  rarity = "epic"
  tags = [ "carbon_fiber_d.va" ]
[skins.white-rabbit]
  name = "White Rabbit"
  rarity = "epic"
  tags = [ "white_rabbit_d.va" ]
[skins.taegeukgi]
  name = "Taegeukgi"
  rarity = "epic"
  event = "Summer Games"
  # Taegukgi also spelled as Taegeukgi
  tags = [ "taegeukgi_d.va", "taegukgi_d.va" ]
[skins.junker]
  name = "Junker"
  rarity = "legendary"
  tags = [ "junker_d.va" ]
[skins.scavenger]
  name = "Scavenger"
  rarity = "legendary"
  tags = [ "scavenger_d.va" ]
[skins.bva]
  name = "B.Va"
  rarity = "legendary"
  tags = [ "b.va_(overwatch)" ]
[skins.junebug]
  name = "Junebug"
  rarity = "legendary"
  tags = [ "junebug_d.va" ]
[skins.black-cat]
  name = "Black Cat"
  rarity = "legendary"
  tags = [ "black_cat_d.va" ]
[skins.palanquin]
  name = "Palanquin"
  rarity = "legendary"
  event = "Year of the Rooster"
  tags = [ "palanquin_d.va" ]
[skins.cruiser]
  name = "Cruiser"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "cruiser_d.va" ]
[skins.police-officer]
  name = "Police Officer"
  rarity = "legendary"
  event = "Heroes of the Storm"
  tags = [ "officer_d.va" ]
[skins.waveracer]
  name = "Waveracer"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "waveracer_d.va" ]
[skins.nano-cola]
  name = "Nano Cola"
  rarity = "legendary"
  event = "D.Va's Nano Cola Challenge"
  tags = [ "nano_cola_d.va" ]

# [skins.shooting_star]
#   name = "Shooting Star"
#   rarity = "common" # ???
#   tags = [ "shooting_star_d.va" ]

# Heroes of the Storm skins
# [skins.the-destroyer]
#   name = "The Destroyer"
#   rarity = "legendary"
#   game = "Heroes of the Storm"
#   tags = [ "d.va_the_destroyer_(overwatch)", "d.va_the_destroyer" ]

