name = "Hanzo"
realName = "Hanzo Shimada"
age = 38
role = "damage"
sex = "male"

tags = [ "hanzo_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.azuki]
  name = "Azuki"
  rarity = "rare"
[skins.kinoko]
  name = "Kinoko"
  rarity = "rare"
[skins.midori]
  name = "Midori"
  rarity = "rare"
[skins.sora]
  name = "Sora"
  rarity = "rare"
[skins.cloud]
  name = "Cloud"
  rarity = "epic"
[skins.dragon]
  name = "Dragon"
  rarity = "epic"
[skins.demon]
  name = "Demon"
  rarity = "epic"
  event = "Halloween Terror"
  tags = [ "demon_hanzo" ]
[skins.kabuki]
  name = "Kabuki"
  rarity = "legendary"
[skins.young-hanzo]
  name = "Young Hanzo"
  rarity = "legendary"
  tags = [ "young_hanzo" ]
[skins.young-master]
  name = "Young Master"
  rarity = "legendary"
  tags = [ "young_master_hanzo" ]
[skins.lone-wolf]
  name = "Lone Wolf"
  rarity = "legendary"
  tags = [ "lone_wolf_hanzo" ]
[skins.okami]
  name = "Okami"
  rarity = "legendary"
  tags = [ "okami_hanzo" ]
[skins.cyberninja]
  name = "Cyberninja"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "cyberninja_hanzo" ]
[skins.casual]
  name = "Casual"
  rarity = "legendary"
  event = "Winter Wonderland"
  tags = [ "casual_hanzo" ]
