name = "Lúcio"
realName = "Lúcio Correia dos Santos"
age = 26
role = "support"
sex = "male"

tags = [ "lucio_correia_dos_santos" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.azul]
  name = "Azul"
  rarity = "rare"
[skins.laranja]
  name = "Laranja"
  rarity = "rare"
[skins.roxo]
  name = "Roxo"
  rarity = "rare"
[skins.vermelho]
  name = "Vermelho"
  rarity = "rare"
[skins.auditiva]
  name = "Auditiva"
  rarity = "epic"
[skins.synaesthesia]
  name = "Synaesthesia"
  rarity = "epic"
[skins.andes]
  name = "Andes"
  rarity = "epic"
  event = "Winter Wonderland"
[skins.capoeira]
  name = "Capoeira"
  rarity = "legendary"
[skins.hippityhop]
  name = "HippityHop"
  rarity = "legendary"
  tags = [ "hippityhop_lucio" ]
[skins.ribbit]
  name = "Ribbit"
  rarity = "legendary"
  tags = [ "ribbit_lucio" ]
[skins.breakaway]
  name = "Breakaway"
  rarity = "legendary"
[skins.slapshot]
  name = "Slapshot"
  rarity = "legendary"
[skins.jazzy]
  name = "Jazzy"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "jazzy_lucio_(overwatch)" ]
[skins.selecao]
  name = "Seleção"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "selecao_lucio_(overwatch)" ]
[skins.striker]
  name = "Striker"
  rarity = "legendary"
  event = "Summer Games"
[skins.equalizer]
  name = "Equalizer"
  rarity = "legendary"
  event = "Retribution"
