name = "McCree"
realName = "Jesse McCree"
age = 37
role = "damage"
sex = "male"

tags = [ "mccree_(overwatch)" ]

[skins.classic]
  name = "classic"
  rarity = "common"
[skins.ebony]
  name = "Ebony"
  rarity = "rare"
[skins.lake]
  name = "Lake"
  rarity = "rare"
[skins.sage]
  name = "Sage"
  rarity = "rare"
[skins.wheat]
  name = "Wheat"
  rarity = "rare"
[skins.on-the-range]
  name = "On the Range"
  rarity = "epic"
[skins.white-hat]
  name = "White Hat"
  rarity = "epic"
[skins.american]
  name = "American"
  rarity = "epic"
  event = "Summer Games"
  tags = [ "american_mccree" ]
[skins.scrooge]
  name = "Scrooge"
  rarity = "epic"
  event = "Winter Wonderland"
  tags = [ "scrooge_mccree" ]
[skins.gambler]
  name = "Gambler"
  rarity = "legendary"
  tags = [ "gambler_mccree" ]
[skins.riverboat]
  name = "Riverboat"
  rarity = "legendary"
  tags = [ "riverboat_mccree" ]
[skins.mystery-man]
  name = "Mystery Man"
  rarity = "legendary"
  tags = [ "mystery_man_mccree" ]
[skins.vigilante]
  name = "Vigilante"
  rarity = "legendary"
  tags = [ "vigilante_mccree" ]
[skins.blackwatch]
  name = "Blackwatch"
  rarity = "legendary"
  event = "Uprising"
  tags = [ "blackwatch_mccree" ]
[skins.lifeguard]
  name = "Lifeguard"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "lifeguard_mccree" ]
[skins.van-helsing]
  name = "Van Helsing"
  rarity = "legendary"
  event = "Halloween Terror"
  tags = [ "van_helsing_mccree" ]
[skins.magistrate]
  name = "Magistrate"
  rarity = "legendary"
  event = "Lunar New Year"
  tags = [ "magistrate_mccree" ]
[skins.scion]
  name = "Scion"
  rarity = "legendary"
  event = "Retribution"
[skins.sherlock]
  name = "Sherlock"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "sherlock_mccree" ]
