name = "Mei"
realName = "Mei-Ling Zhou"
age = 31
role = "defense"
sex = "female"

tags = [ "mei-ling_zhou" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.chrysanthemum]
  name = "Chrysanthemum"
  rarity = "rare"
[skins.heliotrope]
  name = "Heliotrope"
  rarity = "rare"
[skins.jade]
  name = "Jade"
  rarity = "rare"
[skins.persimmon]
  name = "Persimmon"
  rarity = "rare"
[skins.earthen]
  name = "Earthen"
  rarity = "epic"
[skins.snow-plum]
  name = "Snow Plum"
  rarity = "epic"
[skins.ecopoint-antarctica]
  name = "Ecopoint: Antarctica"
  rarity = "legendary"
  tags = [ "ecopoint_mei", "ecopoint_mei_(overwatch)" ]
[skins.firefighter]
  name = "Firefighter"
  rarity = "legendary"
[skins.rescue-mei]
  name = "Rescue Mei"
  rarity = "legendary"
  tags = [ "rescue_mei" ]
[skins.abominable]
  name = "Abominable"
  rarity = "legendary"
  tags = [ "abominable_mei_(overwatch)", "abominable_mei" ]
[skins.yeti-hunter]
  name = "Yeti Hunter"
  rarity = "legendary"
  tags = [ "yeti_hunter_mei_(overwatch)", "yeti_hunter_mei" ]
[skins.change]
  name = "Chang'e"
  rarity = "legendary"
  event = "Year of the Rooster"
  tags = [ "chang'e_mei_(overwatch)", "chang'e_mei" ]
[skins.luna]
  name = "Luna"
  rarity = "legendary"
  event = "Year of the Rooster"
  tags = [ "luna_mei_(overwatch)", "luna_mei" ]
[skins.beekeeper]
  name = "Beekeeper"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "beekeeper_mei_(overwatch)", "beekeeper_mei" ]
[skins.jiangshi]
  name = "Jiangshi"
  rarity = "legendary"
  event = "Halloween Terror"
  tags = [ "jiangshi_mei_(overwatch)", "jiangshi_mei" ]
[skins.mei-rry]
  name = "Mei-rry"
  rarity = "legendary"
  event = "Winter Wonderland"
  tags = [ "mei-rry_mei" ]
[skins.pajamei]
  name = "Pajamei"
  rarity = "legendary"
  event = "Retribution"
