name = "Mei"
realName = "Mei-Ling Zhou"
age = 31
role = "damage"
sex = "female"

tags = [ "mei_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.chrysanthemum]
  name = "Chrysanthemum"
  rarity = "rare"
[skins.heliotrope]
  name = "Heliotrope"
  rarity = "rare"
[skins.jade]
  name = "Jade"
  rarity = "rare"
[skins.persimmon]
  name = "Persimmon"
  rarity = "rare"
[skins.earthen]
  name = "Earthen"
  rarity = "epic"
[skins.snow-plum]
  name = "Snow Plum"
  rarity = "epic"
  tags = [ "snow_plum_mei" ]
[skins.pumpkin]
  name = "Pumpkin"
  rarity = "epic"
  event = "Halloween Terror"
[skins.ecopoint-antarctica]
  name = "Ecopoint: Antarctica"
  rarity = "legendary"
  tags = [ "ecopoint_mei" ]
[skins.firefighter]
  name = "Firefighter"
  rarity = "legendary"
  tags = [ "firefighter_mei" ]
[skins.rescue-mei]
  name = "Rescue Mei"
  rarity = "legendary"
  tags = [ "rescue_mei" ]
[skins.abominable]
  name = "Abominable"
  rarity = "legendary"
  tags = [ "abominable_mei" ]
[skins.yeti-hunter]
  name = "Yeti Hunter"
  rarity = "legendary"
  tags = [ "yeti_hunter_mei" ]
[skins.change]
  name = "Chang'e"
  rarity = "legendary"
  event = "Year of the Rooster"
  tags = [ "chang'e_mei" ]
[skins.luna]
  name = "Luna"
  rarity = "legendary"
  event = "Year of the Rooster"
  tags = [ "luna_mei" ]
[skins.beekeeper]
  name = "Beekeeper"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "beekeeper_mei" ]
[skins.jiangshi]
  name = "Jiangshi"
  rarity = "legendary"
  event = "Halloween Terror"
  tags = [ "jiangshi_mei" ]
[skins.mei-rry]
  name = "Mei-rry"
  rarity = "legendary"
  event = "Winter Wonderland"
  tags = [ "mei-rry_mei" ]
[skins.pajamei]
  name = "Pajamei"
  rarity = "legendary"
  event = "Retribution"
  tags = [ "pajamei" ]
