name = "Mercy"
realName = "Angela Ziegler"
age = 37
role = "support"
sex = "female"

tags = [ "mercy_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.celestial]
  name = "Celestial"
  rarity = "rare"
[skins.mist]
  name = "Mist"
  rarity = "rare"
[skins.orchid]
  name = "Orchid"
  rarity = "rare"
[skins.verdant]
  name = "Verdant"
  rarity = "rare"
[skins.amber]
  name = "Amber"
  rarity = "epic"
[skins.cobalt]
  name = "Cobalt"
  rarity = "epic"
  tags = [ "cobalt_mercy" ]
[skins.fortune]
  name = "Fortune"
  rarity = "epic"
  event = "Year of the Rooster"
  tags = [ "fortune_mercy" ]
[skins.eidgenossin]
  name = "Eidgenossin"
  rarity = "epic"
  event = "Summer Games"
  tags = [ "eidgenossin_mercy" ]
[skins.sigrun]
  name = "Sigrún"
  rarity = "legendary"
  tags = [ "sigrun_mercy" ]
[skins.valkyrie]
  name = "Valkyrie"
  rarity = "legendary"
  tags = [ "valkyrie_mercy" ]
[skins.devil]
  name = "Devil"
  rarity = "legendary"
  tags = [ "devil_mercy" ]
[skins.imp]
  name = "Imp"
  rarity = "legendary"
  tags = [ "imp_mercy" ]
[skins.combat-medic-ziegler]
  name = "Combat Medic Ziegler"
  rarity = "legendary"
  event = "Uprising"
  tags = [ "combat_medic_ziegler" ]
[skins.winged-victory]
  name = "Winged Victory"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "winged_victory_mercy" ]
[skins.witch]
  name = "Witch"
  rarity = "legendary"
  event = "Helloween Terror"
  tags = [ "witch_mercy" ]
[skins.zhuque]
  name = "Zhuque"
  rarity = "legendary"
  event = "Lunar New Year"
  tags = [ "zhuque_mercy" ]
[skins.pink]
  name = "Pink"
  rarity = "legendary"
  event = "BCRF Charity Event 2018"
  tags = [ "pink_mercy" ]
