name = "Reinhardt"
realName = "Reinhardt Wilhelm"
age = 61
role = "tank"
sex = "male"

tags = [ "reinhardt_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.brass]
  name = "Brass"
  rarity = "rare"
[skins.cobalt]
  name = "Cobalt"
  rarity = "rare"
[skins.copper]
  name = "Copper"
  rarity = "rare"
[skins.viridian]
  name = "Viridian"
  rarity = "rare"
[skins.bundeswehr]
  name = "Bundeswehr"
  rarity = "epic"
[skins.paragon]
  name = "Paragon"
  rarity = "epic"
[skins.lieutenant-wilhelm]
  name = "Lieutenant Wilhelm"
  rarity = "epic"
  event = "Uprising"
[skins.coldhardt]
  name = "Coldhardt"
  rarity = "epic"
  event = "Halloween Terror"
[skins.crusader]
  name = "Crusader"
  rarity = "legendary"
  tags = [ "crusader_reinhardt" ]
[skins.blackhardt]
  name = "Blackhardt"
  rarity = "legendary"
  tags = [ "blackhardt_reinhardt" ]
[skins.bloodhardt]
  name = "Bloodhardt"
  rarity = "legendary"
[skins.lionhardt]
  name = "Lionhardt"
  rarity = "legendary"
[skins.stonehardt]
  name = "Stonehardt"
  rarity = "legendary"
  tags = [ "stonehardt_reinhardt" ]
[skins.balderich]
  name = "Balderich"
  rarity = "legendary"
  tags = [ "balderich_reinhardt" ]
[skins.greifhardt]
  name = "Greifhardt"
  rarity = "legendary"
[skins.wujing]
  name = "Wujing"
  rarity = "legendary"
  event = "Year of the Rooster"
  tags = [ "wujing_reinhardt" ]
