name = "Roadhog"
realName = "Mako Rutledge"
age = 48
role = "tank"
sex = "male"

tags = [ "roadhog_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.kiwi]
  name = "Kiwi"
  rarity = "rare"
[skins.mud]
  name = "Mud"
  rarity = "rare"
[skins.sand]
  name = "Sand"
  rarity = "rare"
[skins.thistle]
  name = "Thistle"
  rarity = "rare"
[skins.pigpen]
  name = "Pigpen"
  rarity = "epic"
[skins.stitched]
  name = "Stitched"
  rarity = "epic"
[skins.rudolph]
  name = "Rudolph"
  rarity = "epic"
  event = "Winter Wonderland"
[skins.butcher]
  name = "Butcher"
  rarity = "legendary"
[skins.islander]
  name = "Islander"
  rarity = "legendary"
[skins.toa]
  name = "Toa"
  rarity = "legendary"
[skins.mako]
  name = "Mako"
  rarity = "legendary"
[skins.sharkbait]
  name = "Sharkbait"
  rarity = "legendary"
  tags = [ "sharkbait_roadhog_(overwatch)" ]
[skins.bajie]
  name = "Bajie"
  rarity = "legendary"
  event = "Year of the Rooster"
  tags = [ "bajie_roadhog" ]
[skins.junkensteins-monster]
  name = "Junkenstein's Monster"
  rarity = "legendary"
  event = "Halloween Terror"
  tags = [ "junkenstein's_monster_roadhog" ]
[skins.ice-fisherman]
  name = "Ice Fisherman"
  rarity = "legendary"
  event = "Winter Wonderland"
