name = "Soldier: 76"
realName = "Jack Morrison"
age = 0 # unknown
role = "offense"
sex = "male"

tags = [ "soldier:_76_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.jet]
  name = "Jet"
  rarity = "rare"
[skins.olive]
  name = "Olive"
  rarity = "rare"
[skins.russet]
  name = "Russet"
  rarity = "rare"
[skins.smoke]
  name = "Smoke"
  rarity = "rare"
[skins.bone]
  name = "Bone"
  rarity = "epic"
[skins.golden]
  name = "Golden"
  rarity = "epic"
[skins.immortal]
  name = "Immortal"
  rarity = "epic"
  event = "Halloween Terror"
  tags = [ "immortal_soldier:_76" ]
[skins.venom]
  name = "Venom"
  rarity = "epic"
  event = "Overwatch Anniversary"
[skins.commando76]
  name = "Commando: 76"
  rarity = "legendary"
  tags = [ "commando:_76" ]
[skins.night-ops76]
  name = "Night Ops: 76"
  rarity = "legendary"
[skins.daredevil76]
  name = "Daredevil: 76"
  rarity = "legendary"
  tags = [ "daredevil:_76" ]
[skins.stunt-rider76]
  name = "Stunt Rider: 76"
  rarity = "legendary"
[skins.cyborg76]
  name = "Cyborg: 76"
  rarity = "legendary"
  event = "Overwatch Anniversary"
[skins.grillmaster76]
  name = "Grillmaster: 76"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "grillmaster:_76" ]
[skins.alpine76]
  name = "Alpine: 76"
  rarity = "legendary"
  event = "Winter Wonderland"
[skins.strike-commander-morrison]
  name = "Strike Commander Morrison"
  rarity = "legendary"
  event = "Origins Edition"
  tags = [ "strike_commander_morrison" ]
