name = "Sombra"
realName = "Olivia Colomar"
age = 30
role = "damage"
sex = "female"

tags = [ "sombra_(overwatch)"]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.cidro]
  name = "Cidro"
  rarity = "rare"
[skins.incendio]
  name = "Incendio"
  rarity = "rare"
  tags = [ "incendio_sombra" ]
[skins.mar]
  name = "Mar"
  rarity = "rare"
  tags = [ "mar_sombra" ]
[skins.noche]
  name = "Noche"
  rarity = "rare"
[skins.glitch]
  name = "Glitch"
  rarity = "epic"
  tags = [ "glitch_sombra" ]
[skins.virus]
  name = "Virus"
  rarity = "epic"
  tags = [ "virus_sombra" ]
[skins.peppermint]
  name = "Peppermint"
  rarity = "epic"
  event = "Winter Wonderland"
  tags = [ "peppermint_sombra" ]
[skins.azucar]
  name = "Azúcar"
  rarity = "legendary"
  tags = [ "azucar_sombra" ]
[skins.los-muertos]
  name = "Los Muertos"
  rarity = "legendary"
  tags = [ "los_muertos_sombra" ]
[skins.augmented]
  name = "Augmented"
  rarity = "legendary"
  tags = [ "augmented_sombra" ]
[skins.cyberspace]
  name = "Cyberspace"
  rarity = "legendary"
  tags = [ "cyberspace_sombra" ]
[skins.tulum]
  name = "Tulum"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "tulum_sombra" ]
[skins.rime]
  name = "Rime"
  rarity = "legendary"
  event = "Winter Wonderland"
  tags = [ "rime_sombra" ]
[skins.talon]
  name = "Talon"
  rarity = "legendary"
  event = "Retribution"
  tags = [ "talon_sombra" ]
[skins.demon-hunter]
  name = "Demon Hunter"
  rarity = "legendary"
  event = "BlizzCon 2018"
  tags = [ "demon_hunter_sombra" ]
[skins.bride]
  name = "Bride"
  rarity = "legendary"
  event = "Halloween Terror"
  tags = [ "bride_sombra" ]
