name = "Tracer"
realName = "Lena Oxton"
age = 26
role = "offense"
sex = "female"

tags = [ "tracer_(overwatch)", "lena_oxton" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.electric-purple]
  name = "Electric Purple"
  rarity = "rare"
[skins.hot-pink]
  name = "Hot Pink"
  rarity = "rare"
[skins.neon-green]
  name = "Neon Green"
  rarity = "rare"
[skins.royal-blue]
  name = "Royal Blue"
  rarity = "rare"
[skins.posh]
  name = "Posh"
  rarity = "epic"
[skins.sporty]
  name = "Sporty"
  rarity = "epic"
[skins.rose]
  name = "Rose"
  rarity = "epic"
  event = "Year of the Rooster"
[skins.lightning]
  name = "Lightning"
  rarity = "epic"
  event = "Overwatch Anniversary"
[skins.punk]
  name = "Punk"
  rarity = "legendary"
  tags = [ "punk_tracer_(overwatch)" ]
[skins.ultraviolet]
  name = "Ultraviolet"
  rarity = "legendary"
  tags = [ "ultraviolet_tracer_(overwatch)", "ultraviolet_tracer" ]
[skins.mach-t]
  name = "Mach T"
  rarity = "legendary"
  tags = [ "mach_t_(overwatch)" ]
[skins.tracer]
  name = "T.Racer"
  rarity = "legendary"
  tags = [ "t.racer_(overwatch)" ]
[skins.cadet-oxton]
  name = "Cadet Oxton"
  rarity = "legendary"
  event = "Uprising"
  tags = [ "cadet_oxton_(overwatch)", "cadet_oxton" ]
[skins.graffiti]
  name = "Graffiti"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "graffiti_tracer_(overwatch)", "graffiti_tracer" ]
[skins.sprinter]
  name = "Sprinter"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "sprinter_tracer_(overwatch)" ]
[skins.track-and-field]
  name = "Track and Field"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "track_and_field_tracer_(overwatch)" ]
[skins.jingle]
  name = "Jingle"
  rarity = "legendary"
  event = "Winter Wonderland"
  tags = [ "jingle_tracer_(overwatch)" ]
[skins.slipstream]
  name = "Slipstream"
  rarity = "legendary"
  event = "Origins Edition"
  tags = [ "slipstream_tracer_(overwatch)" ]
