name = "Tracer"
realName = "Lena Oxton"
age = 26
role = "damage"
sex = "female"

tags = [ "tracer_(overwatch)" ]

[skins.classic]
  name = "Classic"
  rarity = "common"
[skins.electric-purple]
  name = "Electric Purple"
  rarity = "rare"
[skins.hot-pink]
  name = "Hot Pink"
  rarity = "rare"
[skins.neon-green]
  name = "Neon Green"
  rarity = "rare"
[skins.royal-blue]
  name = "Royal Blue"
  rarity = "rare"
[skins.posh]
  name = "Posh"
  rarity = "epic"
  tags = [ "posh_tracer" ]
[skins.sporty]
  name = "Sporty"
  rarity = "epic"
  tags = [ "sporty_tracer" ]
[skins.rose]
  name = "Rose"
  rarity = "epic"
  event = "Year of the Rooster"
  tags = [ "rose_tracer" ]
[skins.lightning]
  name = "Lightning"
  rarity = "epic"
  event = "Overwatch Anniversary"
  tags = [ "lightning_tracer" ]
[skins.punk]
  name = "Punk"
  rarity = "legendary"
  tags = [ "punk_tracer" ]
[skins.ultraviolet]
  name = "Ultraviolet"
  rarity = "legendary"
  tags = [ "ultraviolet_tracer" ]
[skins.mach-t]
  name = "Mach T"
  rarity = "legendary"
  tags = [ "mach_t_tracer" ]
[skins.tracer]
  name = "T.Racer"
  rarity = "legendary"
  tags = [ "t.racer" ]
[skins.cadet-oxton]
  name = "Cadet Oxton"
  rarity = "legendary"
  event = "Uprising"
  tags = [ "cadet_oxton" ]
[skins.graffiti]
  name = "Graffiti"
  rarity = "legendary"
  event = "Overwatch Anniversary"
  tags = [ "graffiti_tracer" ]
[skins.sprinter]
  name = "Sprinter"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "sprinter_tracer" ]
[skins.track-and-field]
  name = "Track and Field"
  rarity = "legendary"
  event = "Summer Games"
  tags = [ "track_and_field_tracer" ]
[skins.jingle]
  name = "Jingle"
  rarity = "legendary"
  event = "Winter Wonderland"
  tags = [ "jingle_tracer" ]
[skins.slipstream]
  name = "Slipstream"
  rarity = "legendary"
  event = "Origins Edition"
  tags = [ "slipstream_tracer" ]
[skins.hong-gildong]
  name = "Hong Gildong"
  rarity = "legendary"
  event = "Lunar New Year"
  tags = [ "hong_gildong_tracer" ]
